fix: Check if remote exists, allow merge for unrelated histories

diff --git a/scripts/update b/scripts/update
--- a/scripts/update
+++ b/scripts/update
@@ -2,10 +2,16 @@
 
 set -e
 
-git remote add template https://github.com/achillesrasquinha/docker-template
+echo "Checking if remote exists..."
+git ls-remote --exit-code template
+
+if test $? = 0; then
+    echo "Remote not found. Adding remote template..."
+    git remote add template https://github.com/achillesrasquinha/docker-template
+fi
 
 echo "Fetching updates..."
 git fetch --all
 
 echo "Merging changes..."
-git merge template/develop
+git merge template/develop --allow-unrelated-histories
